### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by Skarwild** [Kaixhin/rlenvs#16]
Did you test your reinforcement learning algorithm with the Minecraft environment ?
Which results did you get ?

**Comment by Kaixhin** [comment]
I have not tested any RL algorithms with Minecraft beyond running Microsoft's provided code to make sure that the interface was working.

**Comment by petrosgk** [comment]
I have tested DRQN here: https://github.com/petrosgk/Atari/tree/minecraft
